version: "3"
services:
  db:
    image: kartoza/postgis
    env_file:
      - docker.env
    volumes:
      - ./db:/var/lib/postgresql/
    ports:
      - 5432:5432
  django:
    build: .
    working_dir: /peakdb/hauban
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver -v 2 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - db



